#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

PATH=$PATH:/home/rockhight/.local/bin/statusbar

picom -f &
dunst &			# dunst for notifications
dwmblocks &
mpd &
flameshot &

xrandr | grep -q "HDMI-1" ;
if [ $? -eq 0 ]
then
	xrandr --output HDMI-1 --primary --left-of eDP-1 & 
fi

feh --randomize --bg-fill ~/images/background/* --randomize --bg-fill ~/images/background/* &
udiskie &
#for executing dwm
# change screen position
pulseaudio --start &

exec dwm 
